title: The TX-Oriented Lemmas
author: Rex Kim (@suneastrex27)
email: root@rex.kim
url: https://rex.kim
baseurl: "/"
description: > 
  I break assumptions.

permalink: /:slug.html

favicon: "logo.png"

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: compressed

plugins:
  - jekyll-feed
